# Generated by Django 4.2.10 on 2024-05-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название индивидуального предпринимателя')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'индивидуальный предприниматель',
                'verbose_name_plural': 'индивидуальные предприниматели',
            },
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'контактные данные', 'verbose_name_plural': 'контактные данные'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'завод', 'verbose_name_plural': 'заводы'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'verbose_name': 'розничная сеть', 'verbose_name_plural': 'розничные сети'},
        ),
        migrations.RemoveField(
            model_name='factory',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='provider',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(max_length=200, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country',
            field=models.CharField(max_length=200, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=200, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='street',
            field=models.CharField(max_length=200, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_model',
            field=models.CharField(max_length=100, verbose_name='модель продукта'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность'),
        ),
        migrations.DeleteModel(
            name='IndividualEntrepreneur',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.contacts', verbose_name='контактные данные'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.products', verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='provider_from_factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.factory', verbose_name='поставки с завода'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='provider_from_retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.retail', verbose_name='поставки с розничной сети'),
        ),
    ]
