# Generated by Django 5.0.4 on 2024-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_rename_individualentrepreneur_entrepreneur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='provider',
        ),
    ]
