# Generated by Django 4.2.10 on 2024-05-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_entrepreneur_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='provider_from_factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.factory', verbose_name='поставки с завода'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='provider_from_retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.retail', verbose_name='поставки с розничной сети'),
        ),
    ]
