# Generated by Django 5.0.4 on 2024-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_remove_factory_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='debt',
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность'),
        ),
    ]
